### ISSUE TITLE
cx_bn_mod_add behaviour

### ISSUE THREAD

**Issue by dkoreshkov** [LedgerHQ/ledger-secure-sdk#175]
Hello,

I've noticed a kludgy bit of code in lib_cxng/src/cx_math.c:
 
```
CX_CHECK(cx_bn_mod_add(bn_r, bn_a, bn_b, bn_m));
#ifdef ST33K1M5
cx_bn_set_u32(bn_a, 0);
CX_CHECK(cx_bn_mod_sub(bn_r, bn_r, bn_a, bn_m));
#endif // ST33K1M5
```
This is also done without ifdefs elsewhere, e.g. in lib_cxng/src/cx_eddsa.c

Is this a fix for a bug in cx_bn_mod_add, such as incomplete reduction for some range of arguments?
Does it affect just ST33K1M5?

**Comment by srasoamiaramanana-ledger** [comment]
Hello,

There are indeed different behaviors between our secure elements but these are under NDA. That is to say it's not a bug and as you noticed, on the ST33K1M5, a subtraction by 0 is required at the end of successive modular operations.
