### ISSUE TITLE
Glyphs bloating built binaries

### ISSUE THREAD

**Issue by aido** [LedgerHQ/ledger-secure-sdk#457]
Hi,

When building an app for several devices all glyphs for each device type are stored in the same `glyphs/` subdirectory of a project:

The following line in the `Makefile.glyphs` file then searches the `glyphs/` directory and its subdirectories and includes all the found glyphs in the compiled `app.elf` binary.
https://github.com/LedgerHQ/ledger-secure-sdk/blob/ef27df1537992b0bbb52563bda309cae70fcdfa3/Makefile.glyphs#L37

This means that all glyphs are included in every device binary i.e. Stax only glyphs will be included in a Nano S binary, This bloats the size of a binary unnecessarily.

I think this happens in all Ledger SDKs.. Can each SDK's `Makefile.glyphs` be changed to look in a `glyphs/$TARGET` subdirectory so that for example Nano S glyphs can be found in `glyphs/nanos` and Stax glyphs in `glyphs/stax`? This will prevent the larger Stax glyphs ending up in Nano S binaries and vice versa.

Another possibility is to just remove that line from `Makefile.glyphs` and let the user take care of it in their own project `Makefile`.

A third possibility that would be backwards compatible would be change `Makefile.glyphs` to do something like this:
```make
ifeq ($(TARGET_NAME),TARGET_STAX)
# Stax glyphs files and generation script
GLYPH_FILES += $(addprefix $(BOLOS_SDK)/lib_nbgl/glyphs/,$(sort $(notdir $(shell find $(BOLOS_SDK)/lib_nbgl/glyphs/))))
ifneq (,$(wildcard glyphs/stax/))
GLYPH_FILES += $(addprefix glyphs/stax/,$(sort $(notdir $(shell find glyphs/stax/))))
else ifneq (,$(wildcard glyphs/))
GLYPH_FILES += $(addprefix glyphs/,$(sort $(notdir $(shell find glyphs/))))
endif
ifneq (,$(wildcard $(ICONNAME)))
# Do not try to generate app icon glyph, if image does not exist
GLYPH_FILES += $(ICONNAME)
endif
ICON_SCRIPT = $(BOLOS_SDK)/lib_nbgl/tools/icon2glyph.py
GENERATE_GLYPHS_CMD = python3 $(ICON_SCRIPT) --glyphcfile $(GLYPH_FILES)
else
# Nano glyphs files and generation script
ifeq ($(TARGET_NAME),TARGET_NANOS)
ifneq (,$(wildcard glyphs/nanos/))
GLYPH_FILES += $(addprefix glyphs/nanos/,$(sort $(notdir $(shell find glyphs/nanos/))))
else ifneq (,$(wildcard glyphs/))
GLYPH_FILES += $(addprefix glyphs/,$(sort $(notdir $(shell find glyphs/))))
endif
else
ifneq (,$(wildcard glyphs/nanox/))
GLYPH_FILES += $(addprefix glyphs/nanox/,$(sort $(notdir $(shell find glyphs/nanox/))))
else ifneq (,$(wildcard glyphs/))
GLYPH_FILES += $(addprefix glyphs/,$(sort $(notdir $(shell find glyphs/))))
endif
endif
GLYPH_FILES += $(addprefix $(BOLOS_SDK)/lib_ux/glyphs/,$(sort $(notdir $(shell find $(BOLOS_SDK)/lib_ux/glyphs/))))
ICON_SCRIPT = $(BOLOS_SDK)/icon3.py
GENERATE_GLYPHS_CMD = python3 $(ICON_SCRIPT) --factorize --glyphcfile $(GLYPH_FILES)
endif
```
i.e. search `glyphs/stax` directory if it exists otherwise search entire `glyphs` directory. 

I am currently using a sloppy workaround in my project `Makefile` to workaround this issue:
```make
ifeq ($(TARGET_NAME), TARGET_NANOS)
    ICONNAME=images/glyphs/nanos/seed_nanos.gif
    GLYPH_FILES += $(addprefix images/glyphs/common/,$(sort $(notdir $(shell find images/glyphs/common/))))
    GLYPH_FILES += $(addprefix images/glyphs/nanos/,$(sort $(notdir $(shell find images/glyphs/nanos/))))
else ifeq ($(TARGET_NAME), TARGET_NANOX)
    ICONNAME=images/glyphs/nanox/seed_nanox.gif
    GLYPH_FILES += $(addprefix images/glyphs/common/,$(sort $(notdir $(shell find images/glyphs/common/))))
    GLYPH_FILES += $(addprefix images/glyphs/nanox/,$(sort $(notdir $(shell find images/glyphs/nanox/))))
else ifeq ($(TARGET_NAME), TARGET_NANOS2)
    ICONNAME=images/glyphs/seed_nanox.gif
    GLYPH_FILES += $(addprefix images/glyphs/common/,$(sort $(notdir $(shell find images/glyphs/common/))))
    GLYPH_FILES += $(addprefix images/glyphs/nanox/,$(sort $(notdir $(shell find images/glyphs/nanox/))))
else ifeq ($(TARGET_NAME), TARGET_STAX)
    ICONNAME=images/glyphs/seed_stax_32px.gif
    GLYPH_FILES += $(addprefix images/glyphs/stax/,$(sort $(notdir $(shell find images/glyphs/stax/))))
endif
```

**Comment by tdejoigny-ledger** [comment]
Hello @aido, ty for your PR. 

Did you try to do some tests to check if the size of the binary is really increased ?
During the link step, unused code/data are dropped and are not included in binary...

In addition, there is a `ifeq ($(TARGET_NAME),TARGET_STAX)` in makefile to include the nbgl glyphs only for Stax

**Comment by tdejoigny-ledger** [comment]
@aido if there is no other issue could you please close the issue ?

**Comment by aido** [comment]
Hi @tdejoigny-ledger ,

Further investigation shows that this issue only occurs when I use `make DEBUG=1`.

When glyphs for all devices are stored in the `glyphs/` directory the following occurs when I build for a Nano S device:
```
bash-5.1# BOLOS_SDK=$NANOS_SDK make DEBUG=1
.
.
.
bash-5.1# ls -la build/nanos/bin/app.elf
-rwxrwxrwx    1 root     root        346708 Oct 26 16:58 build/nanos/bin/app.elf
bash-5.1#
bash-5.1# grep -i stax  build/nanos/bin/app.elf
C_bip39_stax_32px_colors
C_bip39_stax_32px_bitmap
C_bip39_stax_32px
C_bip39_stax_64px_colors
C_bip39_stax_64px_bitmap
C_bip39_stax_64px
C_bip39_stax_check_64px_colors
C_bip39_stax_check_64px_bitmap
C_bip39_stax_check_64px
C_bip85_stax_32px_colors
C_bip85_stax_32px_bitmap
C_bip85_stax_32px
C_bip85_stax_64px_colors
C_bip85_stax_64px_bitmap
C_bip85_stax_64px
C_seed_stax_32px_colors
C_seed_stax_32px_bitmap
C_seed_stax_32px
C_seed_stax_64px_colors
C_seed_stax_64px_bitmap
C_seed_stax_64px
C_sskr_stax_32px_colors
C_sskr_stax_32px_bitmap
C_sskr_stax_32px
C_sskr_stax_64px_colors
C_sskr_stax_64px_bitmap
C_sskr_stax_64px
C_sskr_stax_check_64px_colors
C_sskr_stax_check_64px_bitmap
C_sskr_stax_check_64px
bash-5.1#
```
So, all gifs are included in the debug binary.

However, when the glyphs for only a Nano S device are included in the `glyphs/` directory then the following occurs:
```
bash-5.1# BOLOS_SDK=$NANOS_SDK make DEBUG=1
.
.
.
bash-5.1# ls -la build/nanos/bin/app.elf
-rwxrwxrwx    1 root     root        345084 Oct 26 17:03 build/nanos/bin/app.elf
bash-5.1#
bash-5.1# grep -i stax  build/nanos/bin/app.elf
bash-5.1#
```
i.e. a smaller binary containing only the required glyphs.

Since this only seems to happen on DEBUG builds I think it's OK to close this issue.
