### ISSUE TITLE
Fix the issue of unexpected warning icons appearing.

### ISSUE THREAD

**Issue by overcat** [LedgerHQ/ledger-secure-sdk#737]
## Description

The design in the UI does not match the code. I did not add an icon in the code, but it appears in the UI.
<img width="910" alt="1" src="https://github.com/user-attachments/assets/3bd674ef-9979-450a-8716-a9d97ad5e03a">
<img width="834" alt="2" src="https://github.com/user-attachments/assets/cf6d90f1-863d-4f6f-8ce1-7acb093922e2">

https://github.com/lightsail-network/app-stellar/commit/77d6fcc06a49c7cb764426128998392e5003f812

## Your environment
* Stax and Flex
* speculos 0.96
* SDK [v21.2.1](https://github.com/LedgerHQ/ledger-secure-sdk/releases/tag/v21.2.1)

## Steps to reproduce
```
git clone https://github.com/lightsail-network/app-stellar
cd app-stellar
git checkout 77d6fcc06a49c7cb764426128998392e5003f812

# build
sudo docker run --rm -ti -v "$(realpath .):/app" --user $(id -u $USER):$(id -g $USER) ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
BOLOS_SDK=$STAX_SDK make

speculos -m stax --display qt bin/app.elf
```
Enable hash signing in settings.

```
pip install strledger
export LEDGER_PROXY_ADDRESS=127.0.0.1 && export LEDGER_PROXY_PORT=9999
strledger -v sign-hash a85c933d37847689825acbdfeb50e66d791814abf03b9be4bd6450abb6c99616
```
Related code https://github.com/lightsail-network/app-stellar/blob/77d6fcc06a49c7cb764426128998392e5003f812/src/ui/nbgl_hash.c

## Expected behaviour

Warning icon does not appear.

## Actual behaviour

Please refer to the screenshot above.
## Logs

N/A

## Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

## Additional information

What further confuses me is that these warning icons do not appear 100% of the time; they appear and disappear intermittently during testing.
This is the different screenshot generated from running tests yesterday and running tests today, with no changes made to the relevant code. https://github.com/lightsail-network/app-stellar/commit/77d6fcc06a49c7cb764426128998392e5003f812

**Comment by tdejoigny-ledger** [comment]
fixed by https://github.com/LedgerHQ/ledger-secure-sdk/pull/739
cc: @overcat
