### ISSUE TITLE
Fix character loss in detail pairs with text wrapping enabled

### ISSUE THREAD

**Issue by sleepdefic1t** [LedgerHQ/ledger-secure-sdk#749]
## Description

When using the Ledger Secure SDK version 21.3.1, there is a bug with detail pairs where the number of characters at the end of each line is not considered when the text wraps across pages. This results in an inconsistent number of missing characters on each subsequent page.

## Environment

* OS and version: macOS 14.5 (ledger-app-builder)
* Tag that causes this issue: 21.3.1
* Devices affected: Stax and Flex

## Steps to reproduce

1. Use Ledger Secure SDK version 21.3.1 in your app for Stax or Flex
2. Create a detail pair that contains enough text to wrap across multiple lines and pages
3. Observe that the number of characters at the end of each wrapped line is not accounted for on subsequent pages, leading to missing characters

## Expected behaviour

When a detail pair contains text that wraps across pages, the SDK should consider the number of characters at the end of each wrapped line and ensure that the text continues correctly on each subsequent page without any characters being lost.

## Actual behaviour

The number of characters at the end of each wrapped line in a detail pair is not properly accounted for when the text continues onto subsequent pages. This results in an inconsistent number of characters being lost on each page.

## Logs

<table style="width: 100%;">
  <thead>
    <tr>
      <th colspan="2" style="text-align: center;">wrapping: true</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="width: 50%; text-align: center;">
        <img src="https://github.com/user-attachments/assets/b4463dc3-2996-4536-aedc-dab830750600" alt="wrapping-1" style="width: 100px;">
      </td>
      <td style="width: 50%; text-align: center;">
        <img src="https://github.com/user-attachments/assets/b7a6b6a1-065c-4e50-a7bc-f0a933055706" alt="wrapping-2" style="width: 100px;">
      </td>
    </tr>
  </tbody>
</table>

<table style="width: 100%; margin-top: 20px;">
  <thead>
    <tr>
      <th colspan="2" style="text-align: center;">wrapping: false</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="width: 50%; text-align: center;">
        <img src="https://github.com/user-attachments/assets/39304eae-c784-45a1-9839-0e7a8c4a2156" alt="no-wrapping-1" style="width: 100px;">
      </td>
      <td style="width: 50%; text-align: center;">
        <img src="https://github.com/user-attachments/assets/95cc8f91-8b27-45be-be3c-cf8f8f0663a2" alt="no-wrapping-2" style="width: 100px;">
      </td>
    </tr>
  </tbody>
</table>

## Proposed solution

One temporary workaround is to disable text wrapping for detail pairs. This prevents any characters from being lost, but results in less optimal formatting.

The proper fix would involve modifying how the SDK handles rendering wrapped text. It should keep track of the exact number of characters at the end of each wrapped line and ensure that text continues correctly on the next page. The SDK needs to account for these characters when splitting the content across multiple pages to avoid any loss of information.​​​​​​​​​​​​​​​​

**Comment by tdejoigny-ledger** [comment]
FYI @nroggeman-ledger

**Comment by nroggeman-ledger** [comment]
Fixed by https://github.com/LedgerHQ/ledger-secure-sdk/pull/758
