### ISSUE TITLE
Fix number of tag-value pairs displayed in a page for useCaseReviewStreamingContinueExt()

### ISSUE THREAD

**Issue by ajinkyaraj-23** [LedgerHQ/ledger-secure-sdk#775]
## Description

When a skippable operation is started with useCaseReviewStreamingStart. when we provide the tag-value pairs to useCaseReviewStreamingContinueExt(), the page looks like follows:
![image](https://github.com/user-attachments/assets/60dc02b0-6baa-4dbc-b8d8-2a874d30d1bb)
The last pair of tag-value is being shadowed by the buttons. 

## Your environment

* UBUNTU 22.04
* ragger/speculos testing

## Steps to reproduce

* start a skippable operation using useCaseReviewStreamingStart
* send a list of 4 tag-value pairs to useCaseReviewStreamingContinue()

## Expected behaviour

The last pair should be pushed to next screen.

## Actual behaviour

The last pairs is being shadowed by the buttons.

## Proposed solution

I believe the calculation of number of pages is already there for other use cases, which could be used here.

**Comment by tdejoigny-ledger** [comment]
good catch 
ty @ajinkyaraj-23 
we are working on this 
cc: @nroggeman-ledger
